#define MLE_SETCOLOR                   24313
#define PB_SETCOLOR_APPLY              24312
#define PB_SETCOLOR_HELP               24311
#define PB_SETCOLOR_CANCEL             24310
#define PB_SETCOLOR_OK                 24309
#define TXT_SETCOLOR_SAMPLE_SELECTED   24308
#define TXT_SETCOLOR_SAMPLE_TEXT       24307
#define RECT_SETCOLOR_SAMPLE           24306
#define GRP_SETCOLOR_SAMPLE            24305
#define LB_SETCOLOR_BACKGROUND         24304
#define LB_SETCOLOR_FOREGROUND         24303
#define GRP_SETCOLOR_BACKGROUND        24302
#define GRP_SETCOLOR_FOREGROUND        24301
#define IDLG_SETCOLOR                  24300
